source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'RealmMapViewExample' do
  pod 'RealmSwift', '~> 3.0.0-rc.1'
  pod 'RealmSwiftSFRestaurantData', '>=0.4.1'
end
