source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ABFRealmMapViewExample' do
  pod 'Realm', ">=0.96"
  pod 'RBQFetchedResultsController'
  pod 'RealmSFRestaurantData', ">=0.3"

  target 'ABFRealmMapViewExampleTests' do
    inherit! :search_paths
    pod 'Realm/Headers'
  end
end

